const response = [
    {   
        id : "1", 
        nom : "Smoothie", 
        description : "Orange mangue",
        img_src : "images/smoothie1.jpg", 
        unit_price : 4,
        quantités:["1","2","3","4","5","6","7","8","9"]
    },
    {   
        id : "2", 
        nom : "Smoothie", 
        description : "Ananas banane et citron vert",
        img_src : "images/smoothie2.jpg", 
        unit_price : 3,
        quantités:["1","2","3","4","5","6","7","8","9"],
    },
    {   
        id : "3", 
        nom : "Smoothie", 
        description : "Mangue ananas",
        img_src : "images/smoothie3.jpg", 
        unit_price : 2,
        quantités:["1","2","3","4","5","6","7","8","9"],
    } ,
    {   
        id : "4", 
        nom : "Smoothie", 
        description : "Fruits rouges",
        img_src : "images/smoothie4.jpg", 
        unit_price : 2,
        quantités:["1","2","3","4","5","6","7","8","9"],
    },
    {   
        id : "5", 
        nom : "Smoothie", 
        description : "Concombre détox",
        img_src : "images/smoothie5.jpg", 
        unit_price : 2,
        quantités:["1","2","3","4","5","6","7","8","9"],
    },
    {   
        id : "6", 
        nom : "Smoothie", 
        description : "Banane et graines de chia",
        img_src : "images/smoothie6.jpg", 
        unit_price : 2,
        quantités:["1","2","3","4","5","6","7","8","9"],
    },
    {   
        id : "7", 
        nom : "Smoothie", 
        description : "banane et fraises",
        img_src : "images/smoothie7.jpg", 
        unit_price : 2,
        quantités:["1","2","3","4","5","6","7","8","9"],
    },
    {   
        id : "8", 
        nom : "Smoothie", 
        description : "Orange, pomme et citron",
        img_src : "images/smoothie8.jpg", 
        unit_price : 2,
        quantités:["1","2","3","4","5","6","7","8","9"],
    },
    {   
        id : "9", 
        nom : "Smoothie", 
        description : "Tropical, ananas et noix de coco",
        img_src : "images/smoothie9.jpg", 
        unit_price : 2,
        quantités:["1","2","3","4","5","6","7","8","9"],
    }
]
